# FROM pytorch/pytorch:2.6.0-cuda12.6-cudnn9-devel
FROM nvcr.io/nvidia/pytorch:24.08-py3
ARG DEBIAN_FRONTEND=noninteractive
RUN set -x


###### system-level dependencies ######
RUN apt-get update && \
    apt-get install -y git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


###### install cogkit ######
REPO_NAME=cogkit
WORKDIR /app

RUN git https://github.com/thudm/CogKit
WORKDIR CogKit

RUN pip install uv
RUN uv pip install . --system
